import random

greetings = [
    "Hello, World!",
    "Greetings, World.",
    "Yo, world!",
    "Ahoy, World!",
    "Hark! The World dost beckon!",
    "Howdy, World!",
    "h3ll0, w0r1d!",
    "INSERT COIN TO SAY HELLO TO WORLD",
    "Hello... World? Are you even real?",
    "Oh world, thou art greeted by my code.",
    "[Booting]... Hello, World.",
    "Hello, World! Let's do something great.",
    "Oh hey, World... didn’t see you there.",
    "*beep boop* World hello initiated.",
    "Wassup, World!",
    "O World! Thou art now pinged.",
    "Hey World, welcome to the code side!",
    "Greetings, Earthlings!",
    "Salutations, World!",
    "Sup, World? Let’s make some magic.",
    "Hey, World! Ready for some code?",
    "What's good, World?",
    "Hello there, World!",
    "World, are you ready for this?",
    "Hello from the other side of the code!",
    "Hey there, Universe!",
    "World, brace yourself for greatness!",
    "Hola, Mundo! Just kidding... Hello, World!",
    "Hello, World! It's time for some fun.",
    "Alright, World, let’s do this!",
    "Hello, World... or is it?",
    "Welcome to the World of code!",
    "Greetings from the digital frontier!",
    "Hello, World! In case you forgot, I'm here.",
    "Ahoy there, World! Code ahead!",
    "Hello, World... and everything in it.",
    "Welcome to the World of infinite possibilities.",
    "Hello, World! Your code adventure begins now.",
    "Yoohoo, World! Here I come!",
    "World, welcome to the age of programming!",
    "Peekaboo, World! I'm here to code.",
    "Hello, World! Where the magic happens.",
    "Rise and shine, World! Code’s ready."
]

print(random.choice(greetings))